services:
  # Backend Service
  - type: web
    name: ecommerce-backend-dtra
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /

databases:
  # Main Database
  - name: ecommerce-main-db
    databaseName: react-shop
    user: ecommerce-user
    
  # Location Database  
  - name: ecommerce-location-db
    databaseName: location_db
    user: location-user
